{"uuid": "b7418376-4205-4136-b0e5-50cdaefdad18", "children": ["4f470fab-38e1-4ecb-9070-26242852465f"], "befores": [{"name": "browser", "status": "passed", "start": 1683570879558, "stop": 1683570881681}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: ev\nMessage: unexpected alert open: {Alert text : ev}\n  (Session info: chrome=113.0.5672.63)\nStacktrace:\n0   chromedriver                        0x000000010434b598 chromedriver + 4973976\n1   chromedriver                        0x0000000104342913 chromedriver + 4938003\n2   chromedriver                        0x0000000103effcd6 chromedriver + 470230\n3   chromedriver                        0x0000000103f74062 chromedriver + 946274\n4   chromedriver                        0x0000000103f67988 chromedriver + 895368\n5   chromedriver                        0x0000000103f3521f chromedriver + 688671\n6   chromedriver                        0x0000000103f3656e chromedriver + 693614\n7   chromedriver                        0x0000000104305bb7 chromedriver + 4688823\n8   chromedriver                        0x000000010430aa51 chromedriver + 4708945\n9   chromedriver                        0x000000010431140f chromedriver + 4736015\n10  chromedriver                        0x000000010430b91a chromedriver + 4712730\n11  chromedriver                        0x00000001042de87c chromedriver + 4528252\n12  chromedriver                        0x000000010432af28 chromedriver + 4841256\n13  chromedriver                        0x000000010432b0a7 chromedriver + 4841639\n14  chromedriver                        0x000000010433c28f chromedriver + 4911759\n15  libsystem_pthread.dylib             0x00007ff8077d01d3 _pthread_start + 125\n16  libsystem_pthread.dylib             0x00007ff8077cbbd3 thread_start + 15\n\n", "trace": "  File \"/Users/evgenijgravdin/tms_aqa/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijgravdin/tms_aqa/lib/python3.11/site-packages/_pytest/fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/evgenijgravdin/Desktop/tms_aqa_python/conftest.py\", line 20, in browser\n    driver.close()\n  File \"/Users/evgenijgravdin/tms_aqa/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/evgenijgravdin/tms_aqa/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/evgenijgravdin/tms_aqa/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 244, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1683570883227, "stop": 1683570883232}], "start": 1683570879558, "stop": 1683570883232}